### **Q4 Topic: pandas: read_csv, groupby, merge + numpy basics**

 You have students.csv (student_id, name, class) and scores.csv (student_id, subject, score): 

- (a) Read both into DataFrames and merge on student_id. 
- (b) Use groupby to find average score per subject and per student. 
- (c) Add a grade column: 'A' >= 85, 'B' >= 70, 'C' >= 55, 'F' otherwise. 
- (d) Use numpy: mean, standard deviation, 75th percentile of all scores. 
- (e) Predict the output: 
import pandas as pd 
data = {'name':['A','B','A','B'], 
'score':[80,90,70,85]} 
df = pd.DataFrame(data) 
result = df.groupby('name')['score'].mean() 
print(result.to_dict())

**(a) Read both into DataFrames and merge on student_id.**

In [52]:
import pandas as pd

In [53]:
students = pd.read_csv("students.csv", skipinitialspace=True)
scores = pd.read_csv("scores.csv", skipinitialspace=True)

In [41]:
print(students)
print(type(scores))

   student_id     name class
0           1    Alice   10A
1           2      Bob   10A
2           3  Charlie   10B
<class 'pandas.DataFrame'>

**(b) Use groupby to find average score per subject and per student.**

In [42]:
## In order to use the group by we need to merge the both dataframes
data = pd.merge(students, scores,on='student_id')

In [43]:
data

   student_id     name class  subject  score
0           1    Alice   10A     Math     90
1           1    Alice   10A  English     80
2           2      Bob   10A     Math     70
3           2      Bob   10A  English     85
4           3  Charlie   10B     Math     95

In [44]:
## Avg score per subject
subject_average = data.groupby("subject")["score"].mean()

print(subject_average)

subject
English    82.5
Math       85.0
Name: score, dtype: float64

In [45]:
## Avg score per student

subject_average = data.groupby("name")["score"].mean()

print(subject_average)

name
Alice      85.0
Bob        77.5
Charlie    95.0
Name: score, dtype: float64

**(c) Add a grade column: 'A' >= 85, 'B' >= 70, 'C' >= 55, 'F' otherwise.**

In [46]:
def get_grade(score):
    if score >= 85:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 55:
        return "C"
    else:
        return "F"

In [47]:
data["grade"] = data["score"].apply(get_grade)

In [48]:
data

   student_id     name class  subject  score grade
0           1    Alice   10A     Math     90     A
1           1    Alice   10A  English     80     B
2           2      Bob   10A     Math     70     B
3           2      Bob   10A  English     85     A
4           3  Charlie   10B     Math     95     A

**(d) Use numpy: mean, standard deviation, 75th percentile of all scores.**

In [49]:
import numpy as np

In [50]:
type(data['score'])

pandas.Series

In [51]:
mean = np.mean(data['score'])
print(mean)

std = np.std(data['score'])
print(std)

percentile_75 = np.percentile(data['score'], 75)
print(percentile_75)

84.0
8.602325267042627
90.0

(e) Predict the output: 

import pandas as pd 
data = {'name':['A','B','A','B'], 'score':[80,90,70,85]} 
df = pd.DataFrame(data) 
result = df.groupby('name')['score'].mean() 
print(result.to_dict())

{'A': 75.0, 'B': 87.5}